---
- name: オフィシャルサイトサーバーのセットアップ
  hosts: web
  become: true
  roles:
    - role: common
      tags:
        - role_common
    - role: nginx
      tags:
        - role_nginx
    - role: geerlingguy.certbot
      tags:
        - role_certbot
  # certbot ロールでのインストールが通らないため、先に入れておく
  pre_tasks:
    - name: Install snapd
      ansible.builtin.apt:
        name:
          - snapd
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
  tasks:
    - name: nginxの停止・再起動フックは不要のため削除
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/letsencrypt/renewal-hooks/pre/stop_services
        - /etc/letsencrypt/renewal-hooks/post/start_services
    - name: Fix document root permission
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: a-x,go+wx,u+w,a+rX,g+s
    - name: Adjust ufw for circle CI
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp
  # post_tasks:
  #   - name: www.histudy.jp -> histudy.jp へのリダイレクト設定追加
  #     block:
  #       - name: 既にリダイレクト設定があるか確認
  #         ansible.builtin.shell:
  #           cmd: grep -E 'return 301 https://histudy.jp;' /etc/nginx/sites-enabled/default
  #     rescue:
  #       - name: リダイレクト設定
  #         ansible.builtin.lineinfile:
  #           path: /etc/nginx/sites-available/www.histudy.jp
  #           backup: true
  #           insertafter: "^server {"
  #           line: "return 301 https://histudy.jp;"
  #         notify:
  #           - reload nginx
